"""
map_data.py – เก็บข้อมูล grid ของทุกแผนที่ (20×20)
tile_id อ้างอิงตาม tileset ที่ใช้

Tile IDs (Forest Tileset ตัวอย่าง):
  0  = หญ้าธรรมดา (Grass)
  1  = หญ้าสว่าง
  2  = ทางดิน (Path)
  3  = ทางหิน
  4  = ดอกไม้
  5  = ต้นไม้เล็ก

  PORTAL_ID = 99  (ไอเท็มพิเศษ – ประตูมิติ)

Tile IDs (Space Tileset ตัวอย่าง):
  0  = พื้นอวกาศ (Space floor)
  1  = พื้นอวกาศสว่าง
  2  = เส้นทางแผง (Grid path)
  3  = เส้นทางแผงสว่าง
  4  = หินอวกาศ

  TROPHY_ID = 99  (ไอเท็มพิเศษ – ถ้วยรางวัล)
"""

# ─── ค่า ID พิเศษ ────────────────────────────────────────────────────────────
EMPTY = -1  # ช่องโปร่งใส (ไม่วาด)
PORTAL = 99  # Portal (ใช้ใน Map 1, Item layer)
TROPHY = 98  # Trophy (ใช้ใน Map 2, Item layer)
TREE = 5  # Tree placeholder ID

# =============================================================================
#  MAP 1 – FOREST
# =============================================================================

# Layer 0: Grass – พื้นหญ้า (20×20)
MAP1_GRASS = [
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
]

# Layer 1: Path – เส้นทางเดิน (20×20)
MAP1_PATH = [
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [EMPTY] * 20,
    [EMPTY] * 20,
]

# Layer 2: Item – ไอเท็ม (20×20)  Portal อยู่กลางแผนที่
MAP1_ITEM = [
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        PORTAL,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
]

# =============================================================================
#  MAP 2 – SPACE
# =============================================================================

# Layer 0: Grass (Space Floor) – พื้นอวกาศ (20×20)
MAP2_GRASS = [
    [0] * 20,
    [0] * 20,
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
    [0] * 20,
    [0] * 20,
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
    [0] * 20,
    [0] * 20,
]

# Layer 1: Path (Space Grid) – เส้นแผง (20×20)
MAP2_PATH = [
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [
        EMPTY,
        EMPTY,
        EMPTY,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [EMPTY] * 20,
    [EMPTY] * 20,
]

# Layer 2: Item – Trophy อยู่กลาง Map 2
MAP2_ITEM = [
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        TROPHY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
        EMPTY,
    ],
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
    [EMPTY] * 20,
]
